export type Locale = "es" | "en";
export const isLocale = (value: string): value is Locale => value === "es" || value === "en";

const es = {
  metaTitle:"Diseño y rediseño web bilingüe", metaDescription:"Transformamos páginas antiguas en sitios modernos, rápidos y bilingües que generan confianza y oportunidades.",
  nav:["Inicio","Servicios","Proceso","Antes / Después","Proyectos","Nosotros","Contacto"], proposal:"Solicitar propuesta",
  heroKicker:"Diseño web para negocios que están creciendo", heroTitle:"Transformamos páginas antiguas en experiencias digitales que venden.", heroBody:"Sitios modernos y rápidos que conectan con clientes en inglés y español.", heroPrimary:"Transformar mi web", heroSecondary:"Ver antes y después",
  trust:["Diseño personalizado","Inglés + Español","Responsive","Optimizado para Google"],
  problemTitle:"¿Tu página todavía representa a tu negocio?", problemBody:"Una web desactualizada no solo se ve antigua. También hace más difícil que tus clientes confíen, encuentren lo que necesitan y te contacten.", problems:["Diseño que perdió vigencia","La versión móvil cuesta usarla","La información no se encuentra","Carga lenta y poca visibilidad","Solo comunica en un idioma","No convierte visitas en consultas"],
  beforeTitle:"La diferencia se siente en segundos.", beforeBody:"No siempre necesitas empezar de cero. A veces necesitas transformar lo que ya existe.", before:"Antes", after:"Después", drag:"Arrastra para comparar",
  servicesTitle:"Todo lo que tu nueva web necesita.", servicesBody:"Estrategia, diseño y tecnología unidos en una experiencia preparada para crecer.", services:[['Diseño web','Una presencia creada desde cero para tu negocio.'],['Rediseño web','Una transformación completa, sin perder lo que ya funciona.'],['Web bilingüe','Dos idiomas con mensajes naturales para cada audiencia.'],['Responsive','Una experiencia impecable en celular, tablet y escritorio.'],['SEO inicial','Estructura técnica clara para buscadores y clientes.'],['Velocidad','Menos espera, mejor navegación y mejor rendimiento.'],['Mantenimiento','Actualizaciones y soporte después del lanzamiento.']],
  bilingualTitle:"Un negocio. Dos idiomas. Más oportunidades.", bilingualBody:"Tu sitio debe hablar con la misma claridad que tú. Creamos contenido natural para clientes hispanos y angloparlantes.", viewSite:"Ver la experiencia en", languageCopy:{ es:["Atención cercana","Agenda tu consulta","Servicios pensados para ti"], en:["Care you can trust","Book a consultation","Services built around you"] },
  processTitle:"Hacemos fácil lo que parece técnico.", process:[['Analizamos','Entendemos tu negocio, tu web y tus objetivos.'],['Diseñamos','Convertimos la estrategia en una experiencia clara.'],['Desarrollamos','Construimos un sitio rápido, accesible y responsive.'],['Revisamos','Afinamos cada detalle contigo.'],['Publicamos','Lanzamos con todo correctamente configurado.'],['Acompañamos','Seguimos disponibles cuando el sitio ya está online.']],
  portfolioTitle:"Diseño que resuelve problemas reales.", projects:[['Salud dental','Los pacientes no encontraban información ni podían reservar con facilidad.','Nueva arquitectura, versión bilingüe y llamadas a la acción claras.','Una experiencia más simple, confiable y lista para generar consultas.'],['Restaurante local','La experiencia digital no transmitía la calidad del espacio ni del menú.','Dirección visual nueva, navegación móvil y reservas visibles.','Una presencia que invita a descubrir, reservar y volver.']], problem:"Problema", solution:"Solución", result:"Resultado",
  resultsTitle:"Una mejor web cambia cómo perciben tu negocio.", results:["Mejor primera impresión","Más confianza","Más contactos","Mejor experiencia móvil","Mayor velocidad","Presencia profesional","Dos mercados, una sola marca"],
  whyTitle:"Diseñamos para el negocio, no para nuestro portafolio.", whyBody:"Cada decisión tiene una función: explicar mejor, generar confianza o facilitar el próximo paso.", why:[['A medida','Sin plantillas que hagan que tu negocio se vea como todos los demás.'],['Comunicación clara','Sabes qué estamos haciendo, por qué y qué viene después.'],['Pensado para convertir','Jerarquía, contenido y llamadas a la acción con una intención concreta.'],['Soporte real','El lanzamiento no es el final de nuestra relación.']],
  ctaTitle:"Tu negocio ya evolucionó. Tu página web también debería hacerlo.", ctaBody:"Cuéntanos sobre tu negocio y analizaremos cómo mejorar tu presencia digital.", ctaPrimary:"Solicitar análisis", ctaSecondary:"Ver proyectos",
  contactTitle:"Hablemos de tu nueva web.", contactBody:"Completa el formulario. Te responderemos con preguntas claras y próximos pasos concretos.", labels:["Nombre","Empresa","Email","Teléfono (opcional)","Página web actual","Tipo de proyecto","Presupuesto aproximado","Mensaje"], types:["Nueva página web","Rediseño","Web bilingüe","Landing page","Mantenimiento","Otro"], analyze:"Quiero que analicen mi web actual.", send:"Enviar solicitud", sending:"Enviando...", success:"Gracias. Recibimos tu solicitud y te contactaremos pronto.", error:"No pudimos enviar el formulario. Inténtalo nuevamente.", required:"Este campo es obligatorio.", footer:"Diseño y desarrollo web bilingüe para negocios que quieren avanzar.", privacy:"Privacidad", terms:"Términos", rights:"Todos los derechos reservados."
};
const en: typeof es = {
  metaTitle:"Bilingual web design and redesign", metaDescription:"We turn outdated websites into modern, fast, bilingual experiences built to earn trust and create opportunities.",
  nav:["Home","Services","Process","Before / After","Work","About","Contact"], proposal:"Request a proposal",
  heroKicker:"Web design for growing businesses", heroTitle:"We turn outdated websites into digital experiences that sell.", heroBody:"Modern, fast websites that connect with customers in English and Spanish.", heroPrimary:"Transform my website", heroSecondary:"See before and after",
  trust:["Custom design","English + Spanish","Responsive","Google-ready"],
  problemTitle:"Does your website still represent your business?", problemBody:"An outdated website does more than look old. It makes it harder for customers to trust you, find answers, and get in touch.", problems:["A design past its prime","A frustrating mobile experience","Important details are buried","Slow load times and low visibility","Only speaks one language","Visits do not become inquiries"],
  beforeTitle:"The difference is clear in seconds.", beforeBody:"You do not always need to start over. Sometimes you need to transform what you already have.", before:"Before", after:"After", drag:"Drag to compare",
  servicesTitle:"Everything your next website needs.", servicesBody:"Strategy, design, and technology working together in an experience built to grow.", services:[['Web design','A digital presence created from the ground up for your business.'],['Website redesign','A complete transformation that keeps what already works.'],['Bilingual websites','Two languages with natural messaging for each audience.'],['Responsive design','A polished experience on phones, tablets, and desktops.'],['SEO foundation','A clear technical structure for search engines and people.'],['Speed optimization','Less waiting, smoother browsing, and better performance.'],['Maintenance','Updates and support after your website goes live.']],
  bilingualTitle:"One business. Two languages. More opportunities.", bilingualBody:"Your website should communicate as clearly as you do. We write natural experiences for English and Spanish-speaking customers.", viewSite:"View the experience in", languageCopy:{ es:["Atención cercana","Agenda tu consulta","Servicios pensados para ti"], en:["Care you can trust","Book a consultation","Services built around you"] },
  processTitle:"We make the technical feel simple.", process:[['Analyze','We learn about your business, website, and goals.'],['Design','We turn the strategy into a clear experience.'],['Build','We develop a fast, accessible, responsive website.'],['Review','We refine every detail with you.'],['Launch','We publish with the right foundations in place.'],['Support','We stay available after your site is live.']],
  portfolioTitle:"Design that solves real business problems.", projects:[['Dental care','Patients struggled to find information or book an appointment.','A clearer structure, bilingual content, and focused calls to action.','A simpler, more credible experience ready to earn inquiries.'],['Local restaurant','The website did not reflect the quality of the space or menu.','New art direction, mobile-first navigation, and visible reservations.','A presence that encourages people to discover, book, and return.']], problem:"Problem", solution:"Solution", result:"Outcome",
  resultsTitle:"A better website changes how people see your business.", results:["A stronger first impression","More trust","More inquiries","A better mobile experience","Faster performance","A professional presence","Two markets, one brand"],
  whyTitle:"We design for your business, not our portfolio.", whyBody:"Every decision has a job: explain clearly, build trust, or make the next step easier.", why:[['Built around you','No templates that make your business look like everyone else.'],['Clear communication','You always know what we are doing, why it matters, and what comes next.'],['Conversion-minded','Hierarchy, content, and calls to action each serve a clear purpose.'],['Real support','Launch is not the end of our relationship.']],
  ctaTitle:"Your business has evolved. Your website should too.", ctaBody:"Tell us about your business and we will identify ways to improve your digital presence.", ctaPrimary:"Request an analysis", ctaSecondary:"View projects",
  contactTitle:"Let’s talk about your next website.", contactBody:"Complete the form. We will reply with clear questions and practical next steps.", labels:["Name","Company","Email","Phone (optional)","Current website","Project type","Approximate budget","Message"], types:["New website","Redesign","Bilingual website","Landing page","Maintenance","Other"], analyze:"I want you to review my current website.", send:"Send request", sending:"Sending...", success:"Thank you. We received your request and will be in touch soon.", error:"We could not send the form. Please try again.", required:"This field is required.", footer:"Bilingual web design and development for businesses ready to move forward.", privacy:"Privacy", terms:"Terms", rights:"All rights reserved."
};
export const dictionaries = { es, en };
export type Dictionary = typeof es;
